#!/bin/bash

NODE=/opt/node/bin/node
SERVER_JS_FILE=/home/pi/hal/server.js
USER=pi
OUT=/home/pi/hal.log

case "$1" in

start)
	echo "starting HAL: $NODE $SERVER_JS_FILE"
	sudo -u $USER NODE_ENV=production $NODE $SERVER_JS_FILE > $OUT 2>$OUT &
	;;

stop)
	killall $NODE
	;;

*)
	echo "usage: $0 (start|stop)"
esac

exit 0